apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nexus/setup-job.yaml
  - tekton/pipelines
  - tekton/tasks
  - tekton/pvc/maven-repo-pvc.yaml
  - middleware/resources.yaml
  - kuboard/resources.yaml

helmCharts:
  - name: nexus-repository-manager
    repo: https://sonatype.github.io/helm3-charts/
    version: 64.2.0
    releaseName: nexus
    namespace: platform
    valuesFile: nexus/values.yaml
  
  - name: gitea
    repo: https://dl.gitea.io/charts/
    version: 10.6.0
    releaseName: gitea
    namespace: platform
    valuesFile: gitea/values.yaml

namespace: platform
