apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git-clone.yaml
- kaniko-build-native.yaml
- maven-build.yaml
- quarkus-maven-jib-push.yaml
- quarkus-native-build.yaml
- update-gitops-repo.yaml
