gitea:
  admin:
    email: admin@gitea.local
fullnameOverride: gitea
    password: Admin@123
    username: gitea_admin
  config:
    database:
      DB_TYPE: postgres
      HOST: postgresql.middleware.svc.cluster.local:5432
      NAME: gitea
      PASSWD: gitea123
      USER: gitea
    server:
      DOMAIN: gitea.local
      ROOT_URL: https://gitea.local/
      SSH_DOMAIN: gitea.local
persistence:
  enabled: true
  size: 10Gi
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
redis-cluster:
  enabled: false
service:
  http:
    type: ClusterIP
  ssh:
    type: ClusterIP
