apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: local-ca-issuer
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"local-ca-issuer","nginx.ingress.kubernetes.io/backend-protocol":"HTTP","nginx.ingress.kubernetes.io/proxy-body-size":"50m","nginx.ingress.kubernetes.io/proxy-read-timeout":"600","nginx.ingress.kubernetes.io/proxy-send-timeout":"600"},"name":"kuboard","namespace":"kuboard"},"spec":{"ingressClassName":"nginx","rules":[{"host":"kuboard.local","http":{"paths":[{"backend":{"service":{"name":"kuboard","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["kuboard.local"],"secretName":"kuboard-tls"}]}}
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/rewrite-target: /
    creationTimestamp: "2026-01-22T23:31:41Z"
    generation: 1
    name: kuboard
    namespace: kuboard
    resourceVersion: "179090"
    uid: d4243eb1-3a73-41c8-a2ba-7db77d5eaa00
  spec:
    ingressClassName: nginx
    rules:
    - host: kuboard.local
      http:
        paths:
        - backend:
            service:
              name: kuboard
              port:
                number: 80
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - kuboard.local
      secretName: kuboard-tls
  status:
    loadBalancer:
      ingress:
      - ip: 192.168.10.100
kind: List
metadata:
  resourceVersion: ""
