apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"kuboard","namespace":"kuboard"},"spec":{"ports":[{"name":"web","port":80,"targetPort":80},{"name":"agent-tcp","port":10081,"targetPort":10081},{"name":"agent-udp","port":10081,"protocol":"UDP","targetPort":10081}],"selector":{"app":"kuboard"},"type":"ClusterIP"}}
  creationTimestamp: "2026-01-22T23:29:49Z"
  name: kuboard
  namespace: kuboard
  resourceVersion: "29664"
  uid: 34077313-f086-4378-92b0-cedf06739044
spec:
  clusterIP: 10.43.223.115
  clusterIPs:
  - 10.43.223.115
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: agent-tcp
    port: 10081
    protocol: TCP
    targetPort: 10081
  - name: agent-udp
    port: 10081
    protocol: UDP
    targetPort: 10081
  selector:
    app: kuboard
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
