apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-server-config
data:
  DATABASE_HOST: postgresql.middleware.svc.cluster.local
  DATABASE_PORT: "5432"
  POSTGRES_DB: platform
  QUARKUS_REDIS_HOSTS: redis://redis.middleware.svc.cluster.local:6379
  # 生产配置 - 禁用开发功能
  QUARKUS_SWAGGER_UI_ENABLE: "false"
  QUARKUS_DEV_UI_ENABLE: "false"
