apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-server
spec:
  tls:
  - hosts:
    - api-pre.local
    secretName: admin-server-pre-tls
  rules:
  - host: api-pre.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin-server
            port:
              number: 8080
