apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus-pre

resources:
- ../../base
- serviceaccount.yaml
- configmap.yaml
- secret.yaml

commonLabels:
  environment: pre

# 镜像由 Tekton Pipeline 自动更新（native 版本）
images:
- name: nexus-nexus-repository-manager.platform.svc.cluster.local:5000/admin-server
  newTag: jvm-latest

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/serviceAccountName
      value: admin-server-sa
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
      - configMapRef:
          name: admin-server-config
      - secretRef:
          name: admin-server-secret
  target:
    kind: Deployment
    name: admin-server
- path: ingress-patch.yaml
